### ISSUE TITLE
VEM settings are not being saaved

### ISSUE THREAD

**Issue by Bacon702** [DeadlyBossMods/DBM-Voicepack-VEM#2] opened 2015-01-26 23:38 UTC
when i try to select the VEM settings, The settings dont get saved when i log out

**Comment by henryj** [comment] 2015-01-26 23:49
What settings are we talking about? Usually it's something corrupted in
your wtf folder... Try clear all dbm related things there?

**Comment by Bacon702** [comment] 2015-01-27 00:10
It's the settings where turn on VEM itself, This is on a fresh download and reinstall of windows, The issue was there prior to the windows reinstall.

**Comment by henryj** [comment] 2015-01-27 00:15
in the addon list? and other addons work fine? That's odd... Do you have
some kinda addon management plugin which might cause this?

**Comment by Bacon702** [comment] 2015-01-27 00:16
I Don't atleast not that i know of. I Have Elv UI. Does that count?

**Comment by henryj** [comment] 2015-01-27 00:26
No idea. But I'm pretty sure there shouldn't be any code in our addon or
DBM could cause this. So probably try disable all the other addons and just
leave ours on and see what happens? And maybe  try
http://www.curse.com/addons/wow/acp?

**Comment by Mini-Dragon** [comment] 2015-01-27 00:30
Are you using DBM-profile? Remove it.

**Comment by Bacon702** [comment] 2015-01-27 02:44
nope just DBM and VEM

**Comment by Bacon702** [comment] 2015-01-27 02:50
yep just got rid of all the other addons and the issue persists

**Comment by henryj** [comment] 2015-01-27 04:22
Sorry mate. No idea what could have caused this and no one else is having
this similar issue. Probably something prevents the setting to be written
to your disk? like a firewall etc?

**Comment by Deathez** [comment] 2015-02-01 05:52
I'm having the same problem. After I delete all my addons, WTF saves and cache and install the addons I don't even have the option to pick a voice =(

**Comment by Bacon702** [comment] 2015-02-01 06:16
The fix i figured out was to make a brand new profile for DBM. Apparently
alot of ppl are having this issue

**Comment by Deathez** [comment] 2015-02-01 06:20
What do you mean by "make a brand new profile for DBM"?

**Comment by Bacon702** [comment] 2015-02-01 06:30
type /dbm to go tthe DBM settings. then go to the options tab look for the profile option, it should be the last one. then there will be an empty box and right by it will be a" create profile for DBM core options". type in your characters name preferably then youre good to set the VEM settings again. this time it should save. atleast thats what worked for me.

**Comment by Deathez** [comment] 2015-02-01 06:42
Nope still don't work...but at least I can select the voice again. I'm assuming its Elvui or Elvui Shadow and Light addon. I have no trouble before I download Elvui Shadow and Light. For now I'll just have to enable voice every time before I raid or after I reload/re-log.

**Comment by MysticalOS** [comment] 2015-02-03 09:15
The problem is that apparently for some reason some users settings didn't migrate to a new default profile. So settings would not be savable because they had no profile. It was partially resolved in latest DBM release but unfortunately the issue still affects new users (or new characters that are running DBM for first time)
http://forums.elitistjerks.com/topic/133186-resolved-dbm-not-keepingsaving-all-the-settings/
For more information. Basically the work around was exactly what Bacon702 said.

Issue should be fully resolved in DBM alpha version r12670 or higher. (EDIT, and now dbm release 6.0.15)

**Closed as completed** 2015-02-06 01:51 UTC
